name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.x]
        # 필요에 따라 다른 Node.js 버전도 추가할 수 있습니다.

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Enable Corepack
      run: corepack enable

    - name: Set Yarn Version
      run: corepack prepare yarn@3.6.4 --activate

    - name: Get Yarn Cache Directory Path
      id: yarn-cache-dir-path
      run: echo "CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn Dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-v3.6.4
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-

    - name: Install Dependencies
      run: |
        if [[ ${{ steps.yarn-cache.outputs.cache-hit }} != 'true' ]]; then
          yarn install
        fi

    - name: Build Project
      run: yarn build

    - name: Run Tests
      run: yarn test

    - name: Deploy Project
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: yarn deploy
