name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc

    - name: Configure Git User
      run: |
        git config --global user.email "itwillbeoptimal@gmail.com"
        git config --global user.name "itwillbeoptimal"

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Enable Corepack
      run: corepack enable

    - name: Set Yarn Version
      run: corepack prepare yarn@3.6.4 --activate

    - name: Get Yarn Cache Directory Path
      id: yarn-cache-dir-path
      run: echo "CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV

    - name: Cache Yarn Dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ env.CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-v3.6.4
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-

    - name: Install Dependencies
      run: |
        if [[ "${{ steps.yarn-cache.outputs.cache-hit }}" != 'true' || ! -d "node_modules" ]]; then
          yarn install
        fi

    - name: Build Project
      run: yarn build

    # - name: Run Tests
    #   run: yarn test

    - name: Deploy Project
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: yarn deploy
